### ISSUE TITLE
controllers.MapController

### ISSUE THREAD

**Issue by k3ldon** [walrusone/SkyWarsReloaded#1]
can not start... i have the last build...

[07:34:40] [Server thread/INFO]: [SkyWarsReloaded] Enabling SkyWarsReloaded v0.9
[07:34:40] [Server thread/INFO]: [SkyWarsReloaded] Skywars Reloaded Enabled
[07:34:40] [Server thread/ERROR]: Error occurred while enabling SkyWarsReloaded v0.9 (Is it up to date?)
java.lang.NullPointerException
    at com.walrusone.skywars.controllers.MapController.<init>(MapController.java:28) ~[?:?]
    at com.walrusone.skywars.SkyWarsReloaded.onEnable(SkyWarsReloaded.java:143) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by Relicum** [comment]
PerWorldPlugin is the cause of this issue.I say cause the 2 plugins are clashing.
