### ISSUE TITLE
java.lang.NullPointerException - LobbyListener

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#14]
```
[00:12:56] [Server thread/WARN]: [SkyWarsReloaded] Task #389273 for SkyWarsReloaded v2.7.5 generated an exception
java.lang.NullPointerException
    at com.walrusone.skywars.listeners.LobbyListener.removePlayerItems(LobbyListener.java:169) ~[?:?]
    at com.walrusone.skywars.listeners.LobbyListener$2.run(LobbyListener.java:145) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-skywars.jar:git-Spigot-6d16e64-b105298]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-skywars.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-skywars.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-skywars.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-skywars.jar:git-Spigot-6d16e64-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-skywars.jar:git-Spigot-6d16e64-b105298]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by walrusone** [comment]
Fixed in next release.
