### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'glasscolor' cannot be null

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#15]
```
[00:12:56] [Craft Scheduler Thread - 1089/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'glasscolor' cannot be null
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at sun.reflect.GeneratedConstructorAccessor91.newInstance(Unknown Source)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.Util.getInstance(Util.java:382)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at com.walrusone.skywars.dataStorage.DataStorage$1.run(DataStorage.java:268)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:12:56] [Craft Scheduler Thread - 1089/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by walrusone** [comment]
Fixed in next release.
