### ISSUE TITLE
Memory leak? 

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#20]
```

[22:34:12] [Spigot Watchdog Thread/ERROR]: The server has stopped responding!
[22:34:12] [Spigot Watchdog Thread/ERROR]: Please report this to http://www.spigotmc.org/
[22:34:12] [Spigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[22:34:12] [Spigot Watchdog Thread/ERROR]: Spigot version: git-Spigot-f94fe8f-2642f9b (MC: 1.8.7)
[22:34:12] [Spigot Watchdog Thread/ERROR]: ------------------------------
[22:34:12] [Spigot Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Spigot!):
[22:34:16] [Spigot Watchdog Thread/ERROR]: ------------------------------
[22:34:16] [Spigot Watchdog Thread/ERROR]: Current Thread: Server thread
[22:34:16] [Spigot Watchdog Thread/ERROR]:  PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[22:34:16] [Spigot Watchdog Thread/ERROR]:  Stack:
[22:34:23] [Spigot Watchdog Thread/ERROR]:      java.io.BufferedInputStream.<init>(BufferedInputStream.java:203)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      java.io.BufferedInputStream.<init>(BufferedInputStream.java:183)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.RegionFile.a(RegionFile.java:166)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.RegionFileCache.c(RegionFileCache.java:59)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:63)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:25)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1)
[22:34:23] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:928)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[22:34:27] [Spigot Watchdog Thread/ERROR]:      com.walrusone.skywars.controllers.WorldController.loadWorld(WorldController.java:101)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      com.walrusone.skywars.game.GameMap.loadMap(GameMap.java:95)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      com.walrusone.skywars.game.Game.getGameMap(Game.java:107)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      com.walrusone.skywars.game.Game.<init>(Game.java:94)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      com.walrusone.skywars.controllers.GameController.createGame(GameController.java:162)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      com.walrusone.skywars.controllers.GameController$2.run(GameController.java:265)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:34:30] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[22:34:34] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:34:34] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[22:34:34] [Spigot Watchdog Thread/ERROR]:      net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[22:34:34] [Spigot Watchdog Thread/ERROR]:      java.lang.Thread.run(Thread.java:745)
[22:34:34] [Spigot Watchdog Thread/ERROR]: ------------------------------
[22:34:34] [Spigot Watchdog Thread/ERROR]: Entire Thread Dump:
[22:36:17] [Spigot Watchdog Thread/WARN]: Exception in thread "Spigot Watchdog Thread" 
[22:36:20] [Spigot Watchdog Thread/WARN]: java.lang.OutOfMemoryError: Java heap space
[22:36:24] [Spigot Watchdog Thread/WARN]:   at sun.management.ThreadImpl.dumpThreads0(Native Method)
[22:36:24] [Spigot Watchdog Thread/WARN]:   at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
[22:36:29] [Spigot Watchdog Thread/WARN]:   at org.spigotmc.WatchdogThread.run(WatchdogThread.java:76)
[22:39:07] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: Java heap space
[22:40:42] [Netty Epoll Server IO #3/WARN]: Failed to initialize a channel. Closing: [id: 0x638911e0, /127.0.0.1:48491 => /127.0.0.1:30007]
java.lang.OutOfMemoryError: Java heap space
[22:40:42] [Netty Epoll Server IO #3/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
    at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:245) ~[spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:105) ~[spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[22:41:45] [Netty Epoll Server IO #0/DEBUG]: Set listener of net.minecraft.server.v1_8_R3.NetworkManager@33b9fb08 to net.minecraft.server.v1_8_R3.HandshakeListener@47476a4d
[22:41:48] [Timer-1/WARN]: java.lang.OutOfMemoryError: Java heap space
[22:41:53] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[22:42:19] [Netty Epoll Server IO #3/DEBUG]: Set listener of net.minecraft.server.v1_8_R3.NetworkManager@183af35c to net.minecraft.server.v1_8_R3.HandshakeListener@276b31fa
[22:42:19] [Netty Epoll Server IO #2/WARN]: Failed to initialize a channel. Closing: [id: 0xc8a5bfdb, /127.0.0.1:35113 => /127.0.0.1:30007]
java.lang.OutOfMemoryError: Java heap space
[22:43:24] [Netty Epoll Server IO #0/DEBUG]: Set listener of net.minecraft.server.v1_8_R3.NetworkManager@39ac038c to net.minecraft.server.v1_8_R3.HandshakeListener@3b05813
[22:43:24] [Netty Epoll Server IO #1/DEBUG]: Set listener of net.minecraft.server.v1_8_R3.NetworkManager@73fd8fec to net.minecraft.server.v1_8_R3.HandshakeListener@2a2c8ba2
[22:43:24] [Server thread/INFO]: Stopping server
[22:43:28] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.1.10
[22:45:09] [Netty Epoll Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_8_R3.NetworkManager@48a34452 to net.minecraft.server.v1_8_R3.HandshakeListener@42aec67a
[22:45:29] [Netty Epoll Server IO #3/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.OutOfMemoryError: Java heap space
[22:45:29] [Server thread/INFO]: [SkyWarsReloaded] Disabling SkyWarsReloaded v2.8
[22:45:29] [Netty Epoll Server IO #3/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
    at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:245) ~[spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:105) ~[spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[22:45:58] [Netty Epoll Server IO #2/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
    at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:245) ~[spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:105) ~[spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-skywars.jar:git-Spigot-f94fe8f-2642f9b]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

```

Crashed today... with 4GB memory cap and avg 10 players online.

**Comment by L4BORG** [comment]
Update, moved SkyWars to E5-1620v2 (3,7 GHz+/3,9 GHz+) and allocated 8GB of mem for it

with avg. 30 players and peaking on 50 players server would run out of memory after running for 48h straight... it didn't crash this time but it got stuck on 3 TPS with 0 players online.

**Comment by L4BORG** [comment]
```
[22:00:04 INFO]: CONSOLE issued server command: /gc
[22:00:04 INFO]: Uptime: 11 hours 1 minute 6 seconds
[22:00:04 INFO]: Current TPS = 19.01
[22:00:04 INFO]: Maximum memory: 8,125 MB.
[22:00:04 INFO]: Allocated memory: 7,828 MB.
[22:00:04 INFO]: Free memory: 2,911 MB.
[22:00:04 INFO]: World "world": 256 chunks, 12 entities, 32 tiles.
[22:00:04 INFO]: World "map_5": 225 chunks, 4 entities, 28 tiles.
[22:00:04 INFO]: World "map_9": 286 chunks, 5 entities, 32 tiles.
[22:00:04 INFO]: World "map_1": 183 chunks, 12 entities, 34 tiles.
[22:00:04 INFO]: World "map_6": 193 chunks, 4 entities, 28 tiles.
[22:00:04 INFO]: World "map_2": 214 chunks, 5 entities, 32 tiles.
[22:00:04 INFO]: World "map_4": 204 chunks, 12 entities, 25 tiles.
[22:00:04 INFO]: World "map_7": 149 chunks, 5 entities, 17 tiles.
[22:00:04 INFO]: World "map_3": 230 chunks, 8 entities, 79 tiles.
```

**Comment by L4BORG** [comment]
```
[11:44:40 INFO]: CONSOLE issued server command: /gc
[11:44:40 INFO]: Uptime: 1 day 45 minutes 43 seconds
[11:44:40 INFO]: Current TPS = 3.82
[11:44:40 INFO]: Maximum memory: 8,125 MB.
[11:44:40 INFO]: Allocated memory: 8,125 MB.
[11:44:40 INFO]: Free memory: 24 MB.
[22:00:04 INFO]: World "world": 256 chunks, 12 entities, 32 tiles.
[22:00:04 INFO]: World "map_5": 225 chunks, 4 entities, 28 tiles.
[22:00:04 INFO]: World "map_9": 286 chunks, 5 entities, 32 tiles.
[22:00:04 INFO]: World "map_1": 183 chunks, 12 entities, 34 tiles.
[22:00:04 INFO]: World "map_6": 193 chunks, 4 entities, 28 tiles.
[22:00:04 INFO]: World "map_2": 214 chunks, 5 entities, 32 tiles.
[22:00:04 INFO]: World "map_4": 204 chunks, 12 entities, 25 tiles.
[22:00:04 INFO]: World "map_7": 149 chunks, 5 entities, 17 tiles.
[22:00:04 INFO]: World "map_3": 230 chunks, 8 entities, 79 tiles.
```

**Comment by L4BORG** [comment]
UPDATE: I removed some of the plugins one of them was ChunkSpawnerLImiter and it looks much better now so I'm assuming that some plugins don't handle world un/loading very well - I don't really understand how they managed to make such a mess...

It works much better now:

```
[01:30:30 INFO]: CONSOLE issued server command: /gc
[01:30:30 INFO]: Uptime: 13 hours 42 minutes 12 seconds
[01:30:30 INFO]: Current TPS = 20
[01:30:30 INFO]: Maximum memory: 8,125 MB.
[01:30:30 INFO]: Allocated memory: 2,298 MB.
[01:30:30 INFO]: Free memory: 1,031 MB.
[22:00:04 INFO]: World "world": 256 chunks, 12 entities, 32 tiles.
[22:00:04 INFO]: World "map_5": 225 chunks, 4 entities, 28 tiles.
[22:00:04 INFO]: World "map_9": 286 chunks, 5 entities, 32 tiles.
[22:00:04 INFO]: World "map_1": 183 chunks, 12 entities, 34 tiles.
[22:00:04 INFO]: World "map_6": 193 chunks, 4 entities, 28 tiles.
[22:00:04 INFO]: World "map_2": 214 chunks, 5 entities, 32 tiles.
[22:00:04 INFO]: World "map_4": 204 chunks, 12 entities, 25 tiles.
[22:00:04 INFO]: World "map_7": 149 chunks, 5 entities, 17 tiles.
[22:00:04 INFO]: World "map_3": 230 chunks, 8 entities, 79 tiles
```

I'll leave it running for now... for a few days and report back then. Hopefully that's the end of it, if anyone else got the same issues... check out ur plugins!

**Comment by L4BORG** [comment]
```
[03:45:52 INFO]: CONSOLE issued server command: /gc
[03:45:52 INFO]: Uptime: 1 day 15 hours 57 minutes
[03:45:52 INFO]: Current TPS = 20
[03:45:52 INFO]: Maximum memory: 8,125 MB.
[03:45:52 INFO]: Allocated memory: 4,305 MB.
[03:45:52 INFO]: Free memory: 507 MB.
```

It's ok now.

**Comment by walrusone** [comment]
Thanks for the updates. I'm on vacation. That's why I haven't responded earlier.
