### ISSUE TITLE
Could not pass event PlayerQuitEvent to SkyWarsReloaded v2.8

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#26]
```
[01:50:26 ERROR]: Could not pass event PlayerQuitEvent to SkyWarsReloaded v2.8
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:813) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at com.walrusone.skywars.game.Game.playerQuit(Game.java:587) ~[?:?]
        at com.walrusone.skywars.game.Game.deletePlayer(Game.java:530) ~[?:?]
        at com.walrusone.skywars.listeners.PlayerListener.onPlayerQuit(PlayerListener.java:217) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-skywars.jar:git-Spigot-d97e08b-5e85956]
        ... 12 more
```

```
[01:54:51 INFO]: This server is running CraftBukkit version git-Spigot-d97e08b-5e85956 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

**Comment by RobiRami** [comment]
Does this issue happen every time a player leaves ?
