### ISSUE TITLE
SkyWarsReloaded v2.8 generated an exception

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#29]
```
[10:07:56 WARN]: [SkyWarsReloaded] Task #19124 for SkyWarsReloaded v2.8 generated an exception
java.lang.NullPointerException
        at com.walrusone.skywars.utilities.IconMenu.setOption(IconMenu.java:30) ~[?:?]
        at com.walrusone.skywars.listeners.IconMenuController.setOption(IconMenuController.java:51) ~[?:?]
        at com.walrusone.skywars.menus.JoinMenu.updateJoinMenu(JoinMenu.java:167) ~[?:?]
        at com.walrusone.skywars.menus.JoinMenu$3.run(JoinMenu.java:185) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

Those are kits menus?

Since we had kits removed cause some of our players reported they can be somehow hacked? I'm still looking for someone to explain how lol...

**Comment by L4BORG** [comment]
Player that claim that he could "hack" kits didn't not provide evidence or instructions to replicate that so I'm assuming that's resolved. Tho exception still fired....

https://github.com/walrusone/SkyWarsReloaded/blob/7b370fbf565f1778ec5791faa2c9145e59d6bbeb/SkyWarsReloadedPlugin/src/main/java/com/walrusone/skywars/utilities/IconMenu.java

trying to build inv with null? Since we have 0 kits ATM.
