### ISSUE TITLE
Error occurred while disabling SkyWarsReloaded v2.8 (Is it up to date?)

### ISSUE THREAD

**Issue by L4BORG** [walrusone/SkyWarsReloaded#31]
```
[23:01:45 ERROR]: Error occurred while disabling SkyWarsReloaded v2.8 (Is it up to date?)
java.lang.NullPointerException
        at com.walrusone.skywars.dataStorage.DataStorage.savePlayerSync(DataStorage.java:128) ~[?:?]
        at com.walrusone.skywars.controllers.PlayerController.shutdown(PlayerController.java:91) ~[?:?]
        at com.walrusone.skywars.SkyWarsReloaded.onDisable(SkyWarsReloaded.java:282) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:592) [spigot-skywars.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by L4BORG** [comment]
https://github.com/walrusone/SkyWarsReloaded/issues/20 related.
