### ISSUE TITLE
AsyncPlayerChatEvent Error 

### ISSUE THREAD

**Issue by x1p** [walrusone/SkyWarsReloaded#66]
Error on startup of default plugin with everything default, when player (admin/builder) joins:

`[07:52:48] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Skywars v3.4.2-Snapshot
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1352) [custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1267) [custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.walrusone.skywarsreloaded.listeners.ChatListener.onChat(ChatListener.java:184) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[custom-Spigot-1.12.2.jar:git-custom-"4dbd5bf"]
	... 11 more`

**Comment by walrusone** [comment]
Seems to be a config error. The config is saying spawn is set, but when the plugin looks for the spawn location it gets a null (world or location doesn't exist). I'll add another check for the null pointer, but it looks like a configuration issue.
