### ISSUE TITLE
[BUG] I stay invisible after lossing the game

### ISSUE THREAD

**Issue by ChefMC** [walrusone/SkyWarsReloaded#68]
After I lose the game (maybe when win too, but it was not every time) and spectating, after respawn in lobby I stay invisible. Even after joining new game...

![image](https://user-images.githubusercontent.com/3519015/42730253-c9e67a1a-87f8-11e8-9a2d-b9d171d1996d.png)

![image](https://user-images.githubusercontent.com/3519015/42730255-e5ad0188-87f8-11e8-8abd-6dff04e59eb4.png)

![image](https://user-images.githubusercontent.com/3519015/42730257-f3c37fd6-87f8-11e8-9ab3-7623334f2d1c.png)

**Comment by iBars** [comment]
Also how to configure ELO amounts to give?

**Comment by lukasvdgaag** [comment]
Hello!
A SkyWarsReloaded supporter here!

Is there something like an error or something in the console?

**Comment by ChefMC** [comment]
No. Also I have very-very strange bugs. For example which logged in console:

```
[14:33:29] [Server thread/WARN]: net.minecraft.server.v1_12_R1.ExceptionWorldConflict: Failed to check session lock for world located at .\Vertigo, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
[14:33:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:85)
[14:33:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.checkSession(World.java:2812)
[14:33:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1077)
[14:33:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.save(WorldServer.java:1047)
[14:33:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.save(CraftWorld.java:755)
[14:33:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:704)
[14:33:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[14:33:29] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:33:29] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_12_R1.ExceptionWorldConflict: Failed to check session lock for world located at .\Vertigo, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
	at net.minecraft.server.v1_12_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:85) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.World.checkSession(World.java:2812) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:127) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:209) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:316) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:294) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-bacaf92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Disasters on server:**

1. Game is ended, but I still on destroyed arena and can't teleport to lobby by `/sw leave` or `/spawn`:
![2018-07-15_14 14 47](https://user-images.githubusercontent.com/3519015/42735821-9253cfba-8863-11e8-94b3-2177a9c39091.png)

After rejoin we jumped on pressure plate to start new game... and game was started on this old destroyed arena:

![2018-07-15_14 16 29](https://user-images.githubusercontent.com/3519015/42735838-ec862802-8863-11e8-84e8-489804dba2a1.png)

2. NametagEdit prefixes are disappears after joining SkyWars game. You can try make it compatible using [that](https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Developers.creole#cross-plugin-compatibility) (latest section)
![2018-07-15_14 27 50](https://user-images.githubusercontent.com/3519015/42735840-fd3c78fe-8863-11e8-940d-a474f1e46fb6.png)

![2018-07-15_14 38 40](https://user-images.githubusercontent.com/3519015/42735900-23ec22aa-8865-11e8-8e52-70deffcd997f.png)

And some suggestions:

- Handle player as death on first damage by void. If in lobby - teleport to spawn. Without waiting for respawn screen


I went home 30 minutes ago and may forgot some issues

**Comment by lukasvdgaag** [comment]
Some of these bugs are already noticed. But since the contributor of this SkyWars plugin is offline, there is not much we can do about it. I can try fixing it my own by editing the source code. 

About the error... It turns out your world isn't correct. Try removing the session.lock inside the world.

**Comment by ChefMC** [comment]
I removed it long ago. Fix please presented bugs as you can

**Comment by walrusone** [comment]
I'll look into this. I know the invisibility bug is caused by teleports sometimes, but I've been unable to repeat this in my testing.
