### ISSUE TITLE
High CPU usage on more then 100 players.

### ISSUE THREAD

**Issue by brunyman** [walrusone/SkyWarsReloaded#8]
Hi, we run 3 servers with 160 slots, we started to use your plugin about 1 week ago, we used another plugin with no issues with server full at 160 players, but we noticed on your plugin that the cpu usage is about 3 time higher, but not always, for example at about 120 players online sometimes the server goes terrible high on cpu usage, using like 3 time more then normal, also we can spot some errors popping out:

We run spigot 1.8.7 and plugin version 2.7.5

[23:32:47] [Server thread/WARN]: [SkyWarsReloaded] Task #91608 for SkyWarsReloaded v2.7.5 generated an exception
java.lang.NullPointerException
    at com.walrusone.skywars.game.Game$5.run(Game.java:796) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
\

[23:15:19] [Server thread/WARN]: [SkyWarsReloaded] Task #75988 for SkyWarsReloaded v2.7.5 generated an exception
java.lang.NullPointerException
    at com.walrusone.skywars.utilities.IconMenu.setOption(IconMenu.java:30) ~[?:?]
    at com.walrusone.skywars.listeners.IconMenuController.setOption(IconMenuController.java:51) ~[?:?]
    at com.walrusone.skywars.menus.JoinMenu.updateJoinMenu(JoinMenu.java:167) ~[?:?]
    at com.walrusone.skywars.menus.JoinMenu$3.run(JoinMenu.java:185) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
\

[23:07:45] [Server thread/WARN]: [SkyWarsReloaded] Task #69726 for SkyWarsReloaded v2.7.5 generated an exception
java.lang.NullPointerException
    at com.walrusone.skywars.listeners.LobbyListener.removePlayerItems(LobbyListener.java:169) ~[?:?]
    at com.walrusone.skywars.listeners.LobbyListener$2.run(LobbyListener.java:145) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by brunyman** [comment]
Just found one of the servers with an insane amount of CPU usage with 50 players online and about 2h uptime. Just crazy, it was using about half of the dedicated server processor... (i7)
It has (the SkyWars Server) 3Gb ram and about half available

**Comment by plourenco** [comment]
Same happened with me. Still trying to found the cause.

I believe it's the load/unload world, and disk access.

**Comment by Malachiel87** [comment]
Same issue here

**Comment by Malachiel87** [comment]
There is a crash report after 2 days and 400% cpu usage
http://hastebin.com/akusobimif.avrasm

**Comment by plourenco** [comment]
I will try to reduce the load on this version. In case you are interested.

https://www.spigotmc.org/resources/skywarsreloaded-plus.12244/

(Don't use the first version, please wait for second update)

**Comment by Malachiel87** [comment]
Same issue with your version, hope that there will be a update

**Comment by xxBoWiExx** [comment]
waiting for the v2,

thanks a lot for taking this project.
